package models

import (
	"time"

	"github.com/uptrace/bun"
)

// Application is a structure that represents all the
// types of apps we can have on a system
type Application struct {
	bun.BaseModel `bun:"table:applications"`

	ID        int64     `bun:"id,pk,autoincrement"`
	CreatedAt time.Time `bun:"created_at,nullzero,notnull,default:current_timestamp"`
	UpdatedAt time.Time `bun:"updated_at,nullzero,notnull,default:current_timestamp"`

	Name string   `bun:"name,unique:machine_app_name_pid" json:"name,omitempty" jsonschema:"description=path (or name) of the application,example=/usr/sbin/sshd,example=/usr/bin/musl-gcc,example=C:\\Windows\\System32\\svchost.exe,example=wininit.exe,example=System"`
	Args []string `bun:"args" json:"args,omitempty" jsonschema:"description=list of arguments passed to app"` // we cannot put example right now (PR in progress: https://github.com/invopop/jsonschema/pull/31)
	// Endpoints []*ApplicationEndpoint `json:"endpoints" jsonschema:"description=list of network endpoints open by this app"`
	PID uint64 `bun:"pid,unique:machine_app_name_pid" json:"pid,omitempty" jsonschema:"description=processus ID,example=5452,example=19420"`
	// Flows []*Flow `json:"flows" jsonschema:"description=list of flows generated by this app"`
	// User      interface{}            `json:"user,omitempty" jsonschema:"description=user running the app,oneof_ref=#/$defs/LinuxUser;#/$defs/WindowsUser"` // these definitions are manually provided
	Version  string         `bun:"version" json:"version,omitempty"  jsonschema:"description=application version,example=9.8,example=1.2.3"`
	Protocol string         `bun:"protocol" json:"protocol,omitempty" jsonschema:"description=protocol used to talk to the application,example=ssh,example=http"`
	Config   map[string]any `bun:"config,type:json" json:"config,omitempty" jsonschema:"description=application configuration or metadata"`
	CPE      string         `bun:"cpe" json:"cpe,omitempty" jsonschema:"description=application CPE uri,example=cpe:2.3:a:f5:nginx:*:*:*:*:*:*:*:*"`

	MachineID int64    `bun:"machine_id,notnull,unique:machine_app_name_pid"`
	Machine   *Machine `bun:"rel:belongs-to,join:machine_id=id,on_delete:cascade" json:"machine,omitempty" jsonschema:"description=machine hosting this application"`
	// Belongs-to relationship
	PackageID int64    `bun:"package_id,nullzero"`
	Package   *Package `bun:"rel:belongs-to,join:package_id=id" json:"package,omitempty" jsonschema:"description=package providing this application"`
	// Many-to-many relationship
	Users []User `bun:"m2m:user_applications,join:User=Application" json:"users,omitempty" jsonschema:"description=list of users associated with this application"`
	// Many-to-many relationship via ApplicationEndpoint join table
	NetworkInterfaces []*NetworkInterface `bun:"m2m:application_endpoints,join:Application=NetworkInterface" json:"network_interfaces,omitempty" jsonschema:"description=list of network interfaces associated with this application"`
	// Has-many relationship
	Endpoints []*ApplicationEndpoint `bun:"rel:has-many,join:id=application_id" json:"endpoints,omitempty" jsonschema:"description=list of network endpoints open by this app"`
}
