package cmd

import (
	"bytes"
	"context"
	"fmt"
	"os"
	"path/filepath"

	"github.com/google/uuid"
	"github.com/situation-sh/situation/config"
	"github.com/urfave/cli/v2"
)

var refreshIDCmd = cli.Command{
	Name:  "refresh-id",
	Usage: "Regenerate the internal ID of the agent",
	Flags: []cli.Flag{
		&cli.StringFlag{
			Name:     "uuid",
			Required: false,
			Value:    uuid.NewString(),
			Usage:    "Optional UUID to insert into the binary (randomly generated by default)",
		},
	},
	Action: runRefreshIDCmd,
	After:  moveFile,
}

func moveFile(c *cli.Context) error {
	tmpFile, ok := c.Context.Value(contextConfigKey("tmpFile")).(string)
	if !ok {
		return fmt.Errorf("bad value format for 'tmpFile': %v (%T)",
			tmpFile, tmpFile)
	}
	binaryFile, ok := c.Context.Value(contextConfigKey("binaryFile")).(string)
	if !ok {
		return fmt.Errorf("bad value format for 'binaryFile': %v (%T)",
			tmpFile, tmpFile)
	}
	return os.Rename(tmpFile, binaryFile)
}

func runRefreshIDCmd(c *cli.Context) error {
	u, err := uuid.Parse(c.String("uuid"))
	if err != nil {
		return err
	}

	newBytes, err := u.MarshalBinary()
	if err != nil {
		return err
	}

	// get the path to the current executable
	binaryFile, err := os.Executable()
	if err != nil {
		return err
	}
	binaryFile = filepath.Clean(binaryFile)

	// see https://pkg.go.dev/os#Executable
	binaryFile, err = filepath.EvalSymlinks(binaryFile)
	if err != nil {
		return err
	}

	info, err := os.Stat(binaryFile)
	if err != nil {
		return err
	}

	raw, err := os.ReadFile(binaryFile) //#nosec (https://github.com/securego/gosec/issues/821)
	if err != nil {
		return err
	}

	// set a new random ID
	toWrite := bytes.Replace(raw, config.ID[:16], newBytes[:16], 1)

	// create a second file
	// file, err := ioutil.TempFile(os.TempDir(), "situation")
	bak := filepath.Clean(binaryFile + ".bak")
	file, err := os.OpenFile(bak, os.O_CREATE|os.O_RDWR, info.Mode())
	if err != nil {
		return err
	}

	if err := os.Chmod(file.Name(), info.Mode()); err != nil {
		return err
	}

	tmpFile := file.Name()
	defer func() {
		if err := file.Close(); err != nil {
			fmt.Println(err)
		}
	}()

	// write the modified content
	_, err = file.Write(toWrite)
	if err != nil {
		return err
	}

	// update the context
	// this context is sent to the AfterFunc
	c.Context = context.WithValue(c.Context, contextConfigKey("binaryFile"), binaryFile)
	c.Context = context.WithValue(c.Context, contextConfigKey("tmpFile"), tmpFile)

	return nil
}

func init() {
	app.Commands = append(app.Commands, &refreshIDCmd)
}
