name: test

on:
  pull_request:
env:
  test-module-binary: bin/situation-*module-testing-*
  artifact-basename: situation-module-testing

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
      # Setup Go
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23.3"
      - name: Cache module testing binary
        id: cache-mtb
        uses: actions/cache@v4
        env:
          cache-name: cache-mtb
        with:
          path: ${{ env.test-module-binary }}
          key: ${{ runner.os }}-test-${{ env.cache-name }}-${{ hashFiles('**/*.go') }}
      # build the binary
      - if: ${{ steps.cache-mtb.outputs.cache-hit != 'true' }}
        name: Build module testing binaries
        run: make build-test
      - name: Upload module testing binaries
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.artifact-basename }}
          path: ${{ env.test-module-binary }}
          retention-days: 1

  test-linux:
    needs: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image:
          [
            "debian:10",
            "ubuntu:22.04",
            "fedora:36",
            "rockylinux:9.0",
            "alpine:3.17",
            "opensuse/leap:15.6",
          ]
    container:
      image: ${{ matrix.image }}
    steps:
      - name: Download module testing binary
        uses: actions/download-artifact@v4
        with:
          name: ${{ env.artifact-basename }}
          path: bin
      - name: Export binary name
        run: |
          echo "SITUATION=$(ls bin/situation-*linux | tail -n 1)" >> $GITHUB_ENV
          cat $GITHUB_ENV
      - name: Run the binary
        run: |
          chmod +x ${{ env.SITUATION }}
          ${{ env.SITUATION }} -test.v

  test-windows:
    strategy:
      matrix:
        os: [windows-2022, windows-2019]
    needs: build
    runs-on: ${{ matrix.os }}
    steps:
      - name: Download module testing binary
        uses: actions/download-artifact@v4
        with:
          name: ${{ env.artifact-basename }}
          path: bin
      - name: Export binary name
        run: |
          echo "SITUATION=$(ls bin/situation-*.exe | Select-Object -First 1)" >> $env:GITHUB_ENV
          Get-Content $env:GITHUB_ENV
      - name: Run the binary
        run: |
          & $env:SITUATION -test.v

  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5

      - name: Update module docs
        run: make modules-doc

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version-file: "pyproject.toml"

      - name: Install the project
        run: uv sync --all-extras --dev
      - name: Deploy
        run: uv run mkdocs build
