name: test

on:
  pull_request:
    # only go files and this file
    paths:
      - "**/*.go"
      - ".github/workflows/test.yaml"
      - "Makefile"

jobs:
  linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image:
          [
            "debian:10",
            "debian:12",
            "ubuntu:22.04",
            "ubuntu:24.04",
            "fedora:40",
            "fedora:42",
            "rockylinux:8.9",
            "rockylinux:9.3",
            "alpine:3.18",
            "alpine:3.21",
            "opensuse/leap:15.6",
          ]
    container:
      image: ${{ matrix.image }}
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache: true
      - name: Run module tests
        run: go test -v -cover -run 'TestAllModules' ./modules

  windows:
    strategy:
      matrix:
        os: [windows-2022, windows-2019]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache: true
      - name: Run module tests
        run: go test -v -cover -run 'TestAllModules' ./modules -no-module-msi=true -skip-missing-deps=true

  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache: true

      - name: Update module docs
        run: make modules-doc

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version-file: "pyproject.toml"

      - name: Install the project
        run: uv sync --all-extras --dev
      - name: Build docs
        run: uv run mkdocs build
