CREATE TABLE IF NOT EXISTS "subnetworks" ("id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, "created_at" TIMESTAMP NOT NULL DEFAULT current_timestamp, "updated_at" TIMESTAMP NOT NULL DEFAULT current_timestamp, "network_cidr" VARCHAR NOT NULL, "network_addr" text NOT NULL, "mask_size" INTEGER NOT NULL, "ip_version" INTEGER NOT NULL, "gateway" text, "vlan_id" INTEGER, UNIQUE ("network_cidr"));

CREATE TABLE IF NOT EXISTS "machines" ("id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, "created_at" TIMESTAMP NOT NULL DEFAULT current_timestamp, "updated_at" TIMESTAMP NOT NULL DEFAULT current_timestamp, "hostname" VARCHAR, "host_id" VARCHAR, "arch" VARCHAR, "platform" VARCHAR, "distribution" VARCHAR, "distribution_version" VARCHAR, "distribution_family" VARCHAR, "uptime" INTEGER, "agent" VARCHAR, "cpe" VARCHAR, "chassis" VARCHAR, "parent_machine_id" INTEGER, UNIQUE ("agent"));

CREATE TABLE IF NOT EXISTS "cpus" ("id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, "created_at" TIMESTAMP NOT NULL DEFAULT current_timestamp, "updated_at" TIMESTAMP NOT NULL DEFAULT current_timestamp, "model_name" VARCHAR, "vendor" VARCHAR, "cores" INTEGER, "machine_id" INTEGER NOT NULL, UNIQUE ("machine_id"));

CREATE TABLE IF NOT EXISTS "gpus" ("id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, "created_at" TIMESTAMP NOT NULL DEFAULT current_timestamp, "updated_at" TIMESTAMP NOT NULL DEFAULT current_timestamp, "index" INTEGER, "product" VARCHAR, "vendor" VARCHAR, "driver" VARCHAR, "machine_id" INTEGER NOT NULL, CONSTRAINT "machine_gpu_index" UNIQUE ("index", "machine_id"));

CREATE TABLE IF NOT EXISTS "disks" ("id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, "created_at" TIMESTAMP NOT NULL DEFAULT current_timestamp, "updated_at" TIMESTAMP NOT NULL DEFAULT current_timestamp, "name" VARCHAR, "model" VARCHAR, "size" INTEGER, "type" VARCHAR, "controller" VARCHAR, "partitions" json, "machine_id" INTEGER NOT NULL, CONSTRAINT "machine_disk_name" UNIQUE ("name", "machine_id"));

CREATE TABLE IF NOT EXISTS "network_interfaces" ("id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, "created_at" TIMESTAMP NOT NULL DEFAULT current_timestamp, "updated_at" TIMESTAMP NOT NULL DEFAULT current_timestamp, "name" VARCHAR, "mac" VARCHAR, "mac_vendor" VARCHAR, "ip" VARCHAR, "gateway" VARCHAR, "flags" json, "machine_id" INTEGER, CONSTRAINT "machine_nic_name" UNIQUE ("name", "machine_id"));

CREATE TABLE IF NOT EXISTS "network_interface_subnets" ("network_interface_id" INTEGER NOT NULL, "subnetwork_id" INTEGER NOT NULL, "mac_cidr" VARCHAR NOT NULL, PRIMARY KEY ("network_interface_id", "subnetwork_id"), UNIQUE ("mac_cidr"));

CREATE TABLE IF NOT EXISTS "packages" ("id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, "created_at" TIMESTAMP NOT NULL DEFAULT current_timestamp, "updated_at" TIMESTAMP NOT NULL DEFAULT current_timestamp, "name" VARCHAR, "version" VARCHAR, "vendor" VARCHAR, "manager" VARCHAR, "install_time_unix" INTEGER, "files" VARCHAR, "machine_id" INTEGER NOT NULL, CONSTRAINT "name_version_machine_id" UNIQUE ("name", "version", "machine_id"));

CREATE TABLE IF NOT EXISTS "applications" ("id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, "created_at" TIMESTAMP NOT NULL DEFAULT current_timestamp, "updated_at" TIMESTAMP NOT NULL DEFAULT current_timestamp, "name" VARCHAR, "args" VARCHAR, "pid" INTEGER, "version" VARCHAR, "protocol" VARCHAR, "config" json, "cpe" VARCHAR, "machine_id" INTEGER NOT NULL, "package_id" INTEGER, CONSTRAINT "machine_app_name_pid" UNIQUE ("name", "pid", "machine_id"));

CREATE TABLE IF NOT EXISTS "application_endpoints" ("id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, "created_at" TIMESTAMP NOT NULL DEFAULT current_timestamp, "updated_at" TIMESTAMP NOT NULL DEFAULT current_timestamp, "port" integer, "protocol" VARCHAR, "addr" VARCHAR, "tls" json, "fingerprints" json, "application_protocols" VARCHAR, "saas" VARCHAR, "application_id" INTEGER, "network_interface_id" INTEGER, CONSTRAINT "port_protocol_addr_network_interface_id" UNIQUE ("port", "protocol", "addr", "network_interface_id"));

CREATE TABLE IF NOT EXISTS "users" ("id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, "created_at" TIMESTAMP NOT NULL DEFAULT current_timestamp, "updated_at" TIMESTAMP NOT NULL DEFAULT current_timestamp, "uid" VARCHAR NOT NULL, "gid" VARCHAR, "name" VARCHAR, "username" VARCHAR, "domain" VARCHAR, "machine_id" INTEGER NOT NULL, CONSTRAINT "machine_user" UNIQUE ("uid", "machine_id"));

CREATE TABLE IF NOT EXISTS "user_applications" ("id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, "created_at" TIMESTAMP NOT NULL DEFAULT current_timestamp, "updated_at" TIMESTAMP NOT NULL DEFAULT current_timestamp, "user_id" INTEGER NOT NULL, "application_id" INTEGER NOT NULL, "linux" VARCHAR, CONSTRAINT "user_application" UNIQUE ("user_id", "application_id"));

CREATE TABLE IF NOT EXISTS "flows" ("id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, "created_at" TIMESTAMP NOT NULL DEFAULT current_timestamp, "updated_at" TIMESTAMP NOT NULL DEFAULT current_timestamp, "src_application_id" INTEGER, "src_network_interface_id" INTEGER, "src_addr" VARCHAR, "dst_endpoint_id" INTEGER, CONSTRAINT "flow_src_dst" UNIQUE ("src_application_id", "src_addr", "dst_endpoint_id"));